[package]
name = "mefiles"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
walkdir = "2.4.0"
humansize = "2.1.3"
chrono = "0.4.34"
crossterm = "0.27.0"
tui = { package = "ratatui", version = "0.24.0" }
ratatui = "0.29.0"
